timezone: Asia/Bangkok
skip_if_weekend: true
lookback_days: 260
gemini_model: gemini-2.5-flash
news:
  enable: true
  lookback_days: 2
  per_ticker: 3
risk_management:
  default_stop_loss_pct: 0.03
  default_take_profit_pct: 0.06
charts:
  enable: true
tickers: ["TSLA","NVDA","AAPL","MSFT","AMZN","ALAB","PLTR","TSM","AMD","RKLB"]
indices: ["SPY","QQQ"]
commodities: ["USO","BNO"]
fx: ["UUP","FXE"]
per_call_delay_sec: 0.2
google_news_locale:
  hl: "en-US"
  gl: "US"
  ceid: "US:en"
