name: Daily AI Stock Insight

on:
  schedule:
    - cron: "0 2 * * *"  # 09:00 Asia/Bangkok
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-daily:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run main
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          python main.py

      - name: Commit & Push report
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add reports/*.md || true
          git commit -m "chore: daily report $(date -u +'%Y-%m-%d')" || echo "No changes"
          git push || echo "No push"
